# syntax=docker/dockerfile:1
# check=error=true

# This Dockerfile is designed for production, not development.
# Build'n'run by hand:
# docker build -t <%= app_name %> .
# docker run -d -p 80:80 -e RAILS_MASTER_KEY=<value from config/master.key> --name <%= app_name %> <%= app_name %>
#
# This template builds four images, to optimise caching:
# node: the official Node image, used to copy specific node and yarn into the builder image
# base: the base image with shared configuration for builder and production stages
# builder: builds gems and node modules
# production: runs the actual app

# For a containerized dev environment, see Dev Containers: https://guides.rubyonrails.org/getting_started_with_devcontainer.html

# Make sure RUBY_VERSION matches the Ruby version in .tool-versions and .ruby-version
ARG RUBY_VERSION=<%= Gem.ruby_version %>
# Make sure NODE_VERSION matches the NodeJS version in .tool-versions and package.json
ARG NODE_VERSION=<%= node_version %>

# Node image
FROM docker.io/library/node:$NODE_VERSION-alpine AS node

# Build base image
FROM docker.io/library/ruby:$RUBY_VERSION-alpine AS base

# Add the timezone (base image) as it's not configured by default in Alpine
RUN apk add --update --no-cache tzdata && \
    cp /usr/share/zoneinfo/Europe/London /etc/localtime && \
    echo "Europe/London" > /etc/timezone

# Set production environment variables
ENV RAILS_ENV="production"

# Build builder image from base
FROM base AS builder

# Install node
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

WORKDIR /app

# build-base: dependencies for bundle
# node: node includes yarn as a package manager
# postgresql-dev: postgres driver and libraries
# yaml-dev: psych issues
RUN apk add --no-cache build-base postgresql17-dev yaml-dev
RUN npm install -g corepack
RUN corepack enable

# Install gems defined in Gemfile
COPY Gemfile Gemfile.lock ./

# Install gems and remove gem cache
RUN bundler -v && \
    bundle config set --local deployment 'true' && \
    bundle config set --local without 'development test' && \
    bundle config set --local retry 5 && \
    bundle config set --local jobs 4 && \
    bundle install --no-cache && \
    rm -rf /usr/local/bundle/cache

# Install node packages defined in package.json
COPY package.json yarn.lock ./
RUN yarn install --immutable

# Copy all files to /app (except what is defined in .dockerignore)
COPY . .

# Precompile assets
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

# Cleanup to save space in the production image
RUN rm -rf node_modules log/* tmp/* /tmp && \
    rm -rf /usr/local/bundle/cache && \
    rm -rf .env

# Build runtime image from base
FROM base AS production

# The application runs from /app
WORKDIR /app

# Create non-root user and group
RUN addgroup -S appgroup -g 20001 && adduser -S appuser -G appgroup -u 10001

# libpq: required to run postgres
RUN apk add --no-cache libpq

# Copy files generated in the builder image
COPY --from=builder /app /app
COPY --from=builder /usr/local/bundle /usr/local/bundle

# Change ownership only for directories that need write access
RUN chown -R appuser:appgroup /app/tmp

ARG COMMIT_SHA
ENV COMMIT_SHA=$COMMIT_SHA

# Use non-root user
USER 10001

CMD ["./bin/rails", "server"]
